interactions:
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - rotki/1.39.1.dev56+gea6f8670a.d20250613
    method: GET
    uri: https://eth.blockscout.com/api?action=getblocknobytime&closest=before&module=block&timestamp=1601040361
  response:
    body:
      string: '{"message":"OK","result":{"blockNumber":"10932074"},"status":"1"}'
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Origin:
      - '*'
      Access-Control-Expose-Headers:
      - ''
      Cache-Control:
      - max-age=0, private, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 9513b2032e552297-CDG
      Connection:
      - keep-alive
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Tue, 17 Jun 2025 15:49:10 GMT
      Nel:
      - '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}'
      Report-To:
      - '{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=CBxMiCV1UmeC1tnqHVv9wg8aPRRi%2B0DdziWp2BLiFyFwre8NzzbAeHxwQDRk0m6SPlRkCS8A22eKpb86toSWvV5o8TMZSlQhbMFK4H88Xdu1wj58JiwROeK5F4ccyJI0fFp09A%3D%3D"}],"group":"cf-nel","max_age":604800}'
      Server:
      - cloudflare
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Transfer-Encoding:
      - chunked
      X-Request-Id:
      - 9ff872ed8db8f5037e56e1f9d035c944
      alt-svc:
      - h3=":443"; ma=86400
      content-length:
      - '65'
      server-timing:
      - cfL4;desc="?proto=TCP&rtt=116253&min_rtt=103863&rtt_var=40336&sent=4&recv=8&lost=0&retrans=0&sent_bytes=2370&recv_bytes=861&delivery_rate=26957&cwnd=251&unsent_bytes=0&cid=4a7286b29dfabe9e&ts=220&x=0"
    status:
      code: 200
      message: OK
version: 1
