interactions:
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - rotki/1.39.1.dev56+gea6f8670a.d20250613
    method: GET
    uri: https://eth.blockscout.com/api?action=getblocknobytime&closest=before&module=block&timestamp=1539713238
  response:
    body:
      string: '{"message":"OK","result":{"blockNumber":"6527184"},"status":"1"}'
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Origin:
      - '*'
      Access-Control-Expose-Headers:
      - ''
      Cache-Control:
      - max-age=0, private, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 9514d577886b4742-CDG
      Connection:
      - keep-alive
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Tue, 17 Jun 2025 19:08:08 GMT
      Nel:
      - '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}'
      Report-To:
      - '{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=P7%2BWpEb9%2FmQBJB3y9%2Fv76H%2FcSbJawAN7E2HIPCFykdW9wkpBvm9%2FgXD2hp5lTxeCyHpuVRAweSMRG6ODykcV%2F%2Bp3Gs7VNtgBVWB7TBbqRNLWb%2BxbpM%2Bo7nJ10p2%2Bs0yR9zwGXg%3D%3D"}],"group":"cf-nel","max_age":604800}'
      Server:
      - cloudflare
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Transfer-Encoding:
      - chunked
      X-Request-Id:
      - 0e5273ecf4af409064f08062a9f0218f
      alt-svc:
      - h3=":443"; ma=86400
      content-length:
      - '64'
      server-timing:
      - cfL4;desc="?proto=TCP&rtt=178310&min_rtt=107834&rtt_var=93611&sent=4&recv=8&lost=0&retrans=0&sent_bytes=2371&recv_bytes=861&delivery_rate=25964&cwnd=251&unsent_bytes=0&cid=da174cc6a1fff0d7&ts=251&x=0"
    status:
      code: 200
      message: OK
version: 1
