interactions:
- request:
    body: null
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      User-Agent:
      - rotki/1.39.1.dev56+gea6f8670a.d20250613
    method: GET
    uri: https://eth.blockscout.com/api?action=getblocknobytime&closest=before&module=block&timestamp=1539713238
  response:
    body:
      string: '{"message":"OK","result":{"blockNumber":"6527184"},"status":"1"}'
    headers:
      Access-Control-Allow-Credentials:
      - 'true'
      Access-Control-Allow-Origin:
      - '*'
      Access-Control-Expose-Headers:
      - ''
      Cache-Control:
      - max-age=0, private, must-revalidate
      Cf-Cache-Status:
      - DYNAMIC
      Cf-Ray:
      - 9514d3bfdbac7808-CDG
      Connection:
      - keep-alive
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Tue, 17 Jun 2025 19:06:57 GMT
      Nel:
      - '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}'
      Report-To:
      - '{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=oG69GxtkXuT4gfaI%2FyYLotMFrCVEWBdAGE8idQaFXxr3NM5dDngRYEkROras2%2FYc6cMYfHx04MAnTUGujzU6lneFtOhdKi6RaZMz6kf8xWVClvTT2I6TkvS9dx2%2FRFdadlkEpA%3D%3D"}],"group":"cf-nel","max_age":604800}'
      Server:
      - cloudflare
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      Transfer-Encoding:
      - chunked
      X-Request-Id:
      - a98fe37cc51cbaca2ddf4a934056100e
      alt-svc:
      - h3=":443"; ma=86400
      content-length:
      - '64'
      server-timing:
      - cfL4;desc="?proto=TCP&rtt=116298&min_rtt=104855&rtt_var=39722&sent=4&recv=8&lost=0&retrans=0&sent_bytes=2371&recv_bytes=861&delivery_rate=26672&cwnd=251&unsent_bytes=0&cid=f6aee72fe27242a5&ts=213&x=0"
    status:
      code: 200
      message: OK
version: 1
